language: python
python:
  - "3.6"
  
#Markdown linter for README.md  
install:
  - gem install mdl
  
script:
    - mdl README.md
    
before_script: cd src

script:
  - python main.py
  
after_success:
  coveralls
